### ISSUE TITLE
Stochastic EM implementation

### ISSUE THREAD

**Issue by el19yz** [lindermanlab/dirichlet-tucker#1]
The EM algorithm for fitting the DTD model to a tensor of observations $\mathscr{X} \in \mathbb{N}^{M\times N \times P }$ relies on augmentation by a tensor of latent counts $\mathcal{Z} \in \mathbb{N}^{M\times N \times P \times K_M \times K_N \times K_P}$. This augmentation simplifies the EM algorithm, but it increases the memory requirements because it requires allocating a tensor of the size $K_M  \times K_N \times K_P$ _larger_ than the data size. This memory requirement can be prohibitive for large dimensioned $\mathscr{X}$.

To overcome this issue, we can implement a stochastic EM algorithm that performs an EM step on minibatches of data. Suppose that the $M$ and $N$ modes are the batch modes and $P$ is the mode over which the counts sum to a constant. At each iteration, we grab a minibatch $\mathscr{X}^{(b)} \in \mathbb{N}^{B_M \times B_N \times P}$ where $B_M$ and $B_N$ are the respective minibatch sizes of the batch modes.

A single epoch of the stochastic EM algorithm then takes the form of:
```
Inputs:
   - data, shape (M, N, P)
   - mask, shape (M, N, P)
   - prior_params, dataclass of prior parameters
   - params, dataclass of parameters (G, Psi, Phi, Theta)
   - (B_M, B_N), minibatch sizes for batch modes
   - alpha, stochastic learning rate
Outputs:
   - params, dataclass of updated parameters

for b_slice in [(1:B_M, 1:B_N); (B_M:2*B_M, 1:B_N); ... (M-B_M:M, N-B_N:N)]:
    data_b <- SLICE(data, b_slice)
    mask_b <- SLICE(mask_b, b_slice)
    params_b <- SLICE(params, b_slice)
    rolling_stats_b <- SLICE(rolling_stats, b_slice)

    minibatch_stats <- E_STEP(data_b, mask_b, params_b)
    
    rolling_stats_b <- (1-alpha) * rolling_stats + alpha * M/B_M * N/B_N * minibatch_stats

    params_b <- M_STEP(prior_params, rolling_stats_b)
```
and `SLICE` is the input-dependent slice operator. For example, for `params` consisting of $(G, \Psi, \Phi, \theta)$, `SLICE(params, b_slice)` operator with slice `b_slice <- (im:jm, in:jn)` would produce $(G_{im:jm, in:jn, :}, \Psi_{im:jm,:}, \Phi_{in:jn,:}, \theta)$.

**Comment by ezhang94** [comment]
The `model3d.DirichletTuckerDecomp.stochastic_fit` function performs stochastic EM on minibatches of data, as motivated above. The primary components of this algorithm are the following:

## `model3d.DirichletTuckerDecomp.stochastic_fit::em_step`
### Purpose
Local function that executes a single EM step on a minibatch of data

### Procedure
- Gather minibatch of data and mask, and index appropriately into previous parameters and rolling statistics
- Compute expected sufficient statistics of minibatch, `DirichletTuckerDecomp.minibatched_e_step`
- Incorporate minibatch sufficient stats into corresponding subset of rolling statistics
- Update the subset of parameters to maximize the posterior, `DirichletTuckerDecomp.m_step`
- Update the full set of parameters and rolling statistics

### Alternative approach
Selecting the appropriate subset of parameters and rolling statistics (i.e. the ones associated with the batch dimension factors `Psi` and `Phi`) is performed in the local `em_step`, which then passes in the minibatch/subset into the custom `DirichletTuckerDecomp.minibatched_e_step` and the general `DirichletTuckerDecomp.m_step`.

However minibatching/subsetting could be performed within the `DirichletTuckerDecomp.minibatched_e_step` and another additional M-step customized for the stochastic algorithm. The full data, mask, parameters, and statistics would be passed in, plus the minibatch of indices. This may make the local `em_step` function cleaner by pushing lines 339-349 into more internal functions.

## `model3d.DirichletTuckerDecomp.minibatched_e_step`
### Purpose
Computes the expected sufficient statistics given an _unstructured_ input data, i.e. `X` has shape `(B,P)` instead of `(M,N,P)`

### Differences from full-batch E-step
The primary difference from the E-step used by the full-batch algorithm,  `model3d.DirichletTuckerDecomp.e_step`, is how the computation of probabilities and relative probabilities are computed.

Let $B$ be the set of `(m,n)` indices associated with this minibatch,
i.e. $\mathcal{B}=\{ (\mathcal{B}_1^m, \mathcal{B}_1^n), (\mathcal{B}_2^m, \mathcal{B}_2^n), \ldots, (\mathcal{B}_B^m, \mathcal{B}_B^n)\}$.
For any $b=1,\ldots,B$, the calculation of the rate parameter, generally

$$p(x_{m,n,p}) = \sum_{i=1}^{K_M} \sum_{j=1}^{K_N}  \sum_{k=1}^{K_P} \left(g_{i,j,k} \, \psi_{m,i} \, \phi_{n,j} \, \theta_{k,p} \right),$$

then simplifies to
$$p(x_{b,p}) = \sum_{i=1}^{K_M} \sum_{j=1}^{K_N}  \sum_{k=1}^{K_P} \left(g_{i,j,k} \, \psi_{\mathcal{B}_b^m,i} \, \phi_{\mathcal{B}_b^n,j} \, \theta_{k,p} \right),$$

# Evaluations
- 

Notes of potential relevance to future generalization:
- `batch_ndims=2` is hard coded into the `model3d.DirichletTuckerDecomp`
- `batch_ndims=2` is also implicitly hard-coded into the models in the einsum operations
